import type { Prisma } from "@prisma/client";

/**
 * Fake quote requests for local/demo DB (fictional people & addresses).
 * `priceTableVersion` must match the current PriceGlyph hash from seed.
 */
export function mockContactSubmissionsForSeed(
  priceTableVersion: string,
): Prisma.ContactSubmissionCreateManyInput[] {
  const base = new Date("2026-01-15T15:00:00.000Z");

  return [
    {
      createdAt: new Date(base.getTime() - 8 * 24 * 60 * 60 * 1000),
      contactName: "Jordan Avery",
      contactEmail: "jordan.avery.sample@example.com",
      contactPhone: "555-0142",
      eventType: "wedding",
      eventDate: new Date("2026-05-18T12:00:00.000Z"),
      eventTimeLocal: "17:00",
      eventStartAt: new Date("2026-05-18T22:00:00.000Z"),
      eventAddressLine1: "1845 Peachtree Rd NE",
      eventCity: "Atlanta",
      eventState: "GA",
      eventPostalCode: "30309",
      eventLat: 33.808,
      eventLng: -84.384,
      distanceMilesFromBase: 478.2,
      outsideServiceRadius: true,
      setupOutdoor: true,
      letteringRaw: "FOREVER",
      letteringNormalized: "FOREVER",
      estimatedTotalCents: 350_00,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "pending_request",
      proposedAmountCents: 395_00,
      venmoHandle: "jordan-avery-demo",
    },
    {
      createdAt: new Date(base.getTime() - 7 * 24 * 60 * 60 * 1000),
      contactName: "Riley Santos",
      contactEmail: "riley.santos.fake@example.com",
      contactPhone: "555-0198",
      eventType: "birthday",
      eventDate: new Date("2026-04-22T12:00:00.000Z"),
      eventTimeLocal: "14:30",
      eventStartAt: new Date("2026-04-22T19:30:00.000Z"),
      eventAddressLine1: "2200 Barton Springs Rd",
      eventCity: "Austin",
      eventState: "TX",
      eventPostalCode: "78704",
      eventLat: 30.259,
      eventLng: -97.771,
      distanceMilesFromBase: 721.5,
      outsideServiceRadius: true,
      setupOutdoor: false,
      letteringRaw: "SIXTEEN",
      letteringNormalized: "SIXTEEN",
      estimatedTotalCents: 312_00,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "deposit_requested",
      proposedAmountCents: 340_00,
      venmoHandle: "riley-santos-demo",
      depositRequestedAt: new Date(base.getTime() - 6 * 24 * 60 * 60 * 1000),
    },
    {
      createdAt: new Date(base.getTime() - 6 * 24 * 60 * 60 * 1000),
      contactName: "Casey Nguyen",
      contactEmail: "casey.nguyen.sample@example.com",
      contactPhone: null,
      eventType: "baby_shower",
      eventDate: new Date("2026-06-03T12:00:00.000Z"),
      eventTimeLocal: "11:00",
      eventStartAt: new Date("2026-06-03T16:00:00.000Z"),
      eventAddressLine1: "233 S Wacker Dr",
      eventCity: "Chicago",
      eventState: "IL",
      eventPostalCode: "60606",
      eventLat: 41.879,
      eventLng: -87.636,
      distanceMilesFromBase: 385.4,
      outsideServiceRadius: true,
      setupOutdoor: false,
      letteringRaw: "BABY LOVE",
      letteringNormalized: "BABY LOVE",
      estimatedTotalCents: 298_50,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "deposit_paid",
      proposedAmountCents: 325_00,
      venmoHandle: "casey-nguyen-demo",
      depositRequestedAt: new Date(base.getTime() - 5 * 24 * 60 * 60 * 1000),
      depositPaidAt: new Date(base.getTime() - 4 * 24 * 60 * 60 * 1000),
    },
    {
      createdAt: new Date(base.getTime() - 5 * 24 * 60 * 60 * 1000),
      contactName: "Taylor Brooks",
      contactEmail: "taylor.brooks.fake@example.com",
      contactPhone: "555-0167",
      eventType: "wedding",
      eventDate: new Date("2026-07-12T12:00:00.000Z"),
      eventTimeLocal: "18:00",
      eventStartAt: new Date("2026-07-13T00:00:00.000Z"),
      eventAddressLine1: "1595 Wynkoop St",
      eventCity: "Denver",
      eventState: "CO",
      eventPostalCode: "80202",
      eventLat: 39.753,
      eventLng: -105.0,
      distanceMilesFromBase: 892.1,
      outsideServiceRadius: true,
      setupOutdoor: true,
      letteringRaw: "T & K",
      letteringNormalized: "T & K",
      estimatedTotalCents: 275_00,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "booked",
      proposedAmountCents: 310_00,
      venmoHandle: "taylor-brooks-demo",
      depositRequestedAt: new Date(base.getTime() - 4 * 24 * 60 * 60 * 1000),
      depositPaidAt: new Date(base.getTime() - 3 * 24 * 60 * 60 * 1000),
      bookingConfirmedAt: new Date(base.getTime() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      createdAt: new Date(base.getTime() - 4 * 24 * 60 * 60 * 1000),
      contactName: "Jamie Patel",
      contactEmail: "jamie.patel.sample@example.com",
      contactPhone: "555-0123",
      eventType: "other",
      eventDate: new Date("2026-05-02T12:00:00.000Z"),
      eventTimeLocal: "19:30",
      eventStartAt: new Date("2026-05-03T00:30:00.000Z"),
      eventAddressLine1: "501 Commerce St",
      eventCity: "Nashville",
      eventState: "TN",
      eventPostalCode: "37203",
      eventLat: 36.162,
      eventLng: -86.781,
      distanceMilesFromBase: 211.8,
      outsideServiceRadius: true,
      setupOutdoor: false,
      letteringRaw: "OPENING NIGHT",
      letteringNormalized: "OPENING NIGHT",
      estimatedTotalCents: 420_00,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "pending_request",
      proposedAmountCents: null,
      venmoHandle: null,
    },
    {
      createdAt: new Date(base.getTime() - 3 * 24 * 60 * 60 * 1000),
      contactName: "Alex Rivera",
      contactEmail: "alex.rivera.fake@example.com",
      contactPhone: "555-0181",
      eventType: "wedding",
      eventDate: new Date("2026-03-28T12:00:00.000Z"),
      eventTimeLocal: "16:00",
      eventStartAt: new Date("2026-03-28T21:00:00.000Z"),
      eventAddressLine1: "509 Summit Ct",
      eventCity: "Jackson",
      eventState: "MO",
      eventPostalCode: "63755",
      eventLat: 37.553,
      eventLng: -89.668,
      distanceMilesFromBase: 3.2,
      outsideServiceRadius: false,
      setupOutdoor: true,
      letteringRaw: "WELCOME",
      letteringNormalized: "WELCOME",
      estimatedTotalCents: 265_00,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "deposit_requested",
      proposedAmountCents: 265_00,
      venmoHandle: "alex-rivera-demo",
      depositRequestedAt: new Date(base.getTime() - 2 * 24 * 60 * 60 * 1000),
    },
    {
      createdAt: new Date(base.getTime() - 2 * 24 * 60 * 60 * 1000),
      contactName: "Sam Okonkwo",
      contactEmail: "sam.okonkwo.sample@example.com",
      contactPhone: "555-0155",
      eventType: "birthday",
      eventDate: new Date("2026-08-10T12:00:00.000Z"),
      eventTimeLocal: "13:00",
      eventStartAt: new Date("2026-08-10T18:00:00.000Z"),
      eventAddressLine1: "1 Arrowhead Dr",
      eventCity: "Kansas City",
      eventState: "MO",
      eventPostalCode: "64129",
      eventLat: 39.049,
      eventLng: -94.484,
      distanceMilesFromBase: 312.6,
      outsideServiceRadius: true,
      setupOutdoor: true,
      letteringRaw: "GO CHIEFS",
      letteringNormalized: "GO CHIEFS",
      estimatedTotalCents: 330_00,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "cancelled",
      proposedAmountCents: 350_00,
      venmoHandle: "sam-okonkwo-demo",
    },
    {
      createdAt: new Date(base.getTime() - 1 * 24 * 60 * 60 * 1000),
      contactName: "Drew MacKenzie",
      contactEmail: "drew.mackenzie.fake@example.com",
      contactPhone: null,
      eventType: "wedding",
      eventDate: new Date("2026-09-20T12:00:00.000Z"),
      eventTimeLocal: "17:30",
      eventStartAt: new Date("2026-09-20T22:30:00.000Z"),
      eventAddressLine1: "2000 Prentiss Pl",
      eventCity: "Memphis",
      eventState: "TN",
      eventPostalCode: "38112",
      eventLat: 35.149,
      eventLng: -89.977,
      distanceMilesFromBase: 154.7,
      outsideServiceRadius: true,
      setupOutdoor: false,
      letteringRaw: "ALWAYS",
      letteringNormalized: "ALWAYS",
      estimatedTotalCents: 288_00,
      priceTableVersion,
      consentAccepted: true,
      pipelineStatus: "pending_request",
      proposedAmountCents: 305_00,
      venmoHandle: "drew-mackenzie-demo",
    },
  ];
}
